### PR TITLE
Added kick command, and make voice commands require you to be in the voice chat

### PR DESCRIPTION
**Pull request by ajayyy**

### CODE REVIEW

**Comment by ajayyy** [comment]
Should be good I think now

**Comment by ZLima12** [comment]
It's nice that everything's back, but it still isn't on its own branch. Just try to do it that way in the future.

**Comment by ajayyy** [comment]
Yes I know. I tried. I couldn't since everything else was already committed to one branch.

**Comment by ZLima12** [comment]
Alright, no worries.

**Comment by ZLima12** [comment]
Looks good!

**Comment by ajayyy** [comment]
Only issue with invalidating user if they leave the voice chat is they could leave and come back

**Comment by ZLima12** [comment]
Actually, that's a good point. I suppose it would be easier for now to not do that.

**Comment by ZLima12** [comment]
You said you were planning on adding a few more commands, right? When you get a chance, please make an issue with all your ideas so we can coordinate our efforts.

**Comment by ZLima12** [comment]
Also, email me your Discord or something similar so that I don't have to keep talking to you through PRs. :P

**Pull request merged**
